version: '3.3'

services:

  # cart-svc:
  #   container_name: cart-svc
  #   build:
  #     context: ./service-cart
  #     dockerfile: Dockerfile
  #   environment:
  #     - OTEL_SERVICE_NAME=cart-svc
  #     - OTEL_METRICS_EXPORTER=otlp
  #     - OTEL_TRACES_EXPORTER=otlp
  #     - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14250
  #     - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:5555
  #     - OTEL_RESOURCE_ATTRIBUTES=service.name=cart-svc,service.version=0.0.1-SNAPSHOT
  #   ports:
  #     - "8080:8080"

  # inventory-svc:
  #   container_name: inventory-svc
  #   build:
  #     context: ./service-inventory
  #     dockerfile: Dockerfile
  #   environment:
  #     - OTEL_SERVICE_NAME=inventory-svc
  #     - OTEL_METRICS_EXPORTER=otlp
  #     - OTEL_TRACES_EXPORTER=otlp
  #     - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14250
  #     - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:5555
  #     - OTEL_RESOURCE_ATTRIBUTES=service.name=inventory-svc,service.version=0.0.1-SNAPSHOT
  #   ports:
  #     - "8081:8081"

  tempo:
    image: grafana/tempo:1.5.0
    command: [ "-search.enabled=true", "-config.file=/etc/tempo.yaml" ]
    container_name: tempo
    hostname: tempo
    volumes:
      - ./otel-config/tempo-config.yaml:/etc/tempo.yaml
      - ./otel-config/tempo-overrides.yaml:/etc/overrides.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      - "3200:3200"
      - "4317:4317"
    healthcheck:
      interval: 5s
      retries: 10
      test: wget --no-verbose --tries=1 --spider http://localhost:3200/status || exit 1

  
  loki:
    image: grafana/loki:2.8.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    container_name: loki
    hostname: loki


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./otel-config/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
    healthcheck:
      interval: 5s
      retries: 10
      test: wget --no-verbose --tries=1 --spider http://localhost:9090/status || exit 1

  
  collector:
    image: otel/opentelemetry-collector:latest
    container_name: collector
    hostname: collector
    depends_on:
      tempo:
        condition: service_healthy
      prometheus:
        condition: service_healthy
    command: [ "--config=/etc/collector-config.yaml" ]
    volumes:
      - ./otel-config/collector-config.yaml:/etc/collector-config.yaml
    ports:
      - "5555:5555"
      - "6666:6666"


  grafana:
    image: grafana/grafana:9.3.8
    container_name: grafana
    hostname: grafana
    volumes:
      # Note: changed to dynamically generate grafana.ini so env var can be used.
      # - ./otel-config/grafana-bootstrap.ini:/etc/grafana/grafana.ini
      - ./otel-config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    
    # url: http://loki:3100
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://${IP_ADDRESS?"An IP_ADDRESS env variable required."}:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: true
        EOF
        /run.sh
    
    ports:
      - "3000:3000"
    healthcheck:
      interval: 5s
      retries: 10
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1

networks:
  default:
    name: rcl-local-docker
